### ISSUE TITLE
Bug: Overflowing lines

### ISSUE THREAD

**Issue by amiyuki7** [amiyuki7/redqct#3]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/111574544/203289452-2a8f1ba3-8a53-4afa-bc0c-e85f1d7f0284.png">

In the image above, a really long line ends up overflowing - the text is cut off on the right edge of the image

**Comment by VladP1234** [comment]
Everything after the 50th character gets cut off and replaced with "..."
