### ISSUE TITLE
Bug: Custom Activity Bug 

### ISSUE THREAD

**Issue by VladP1234** [amiyuki7/redqct#5]
<img width="1158" alt="Screen Shot 2022-11-23 at 9 18 25 am" src="https://user-images.githubusercontent.com/118417770/203432746-0627cf63-c569-4367-a675-70d49b71ce94.png">

Not supported yet, add support

**Comment by amiyuki7** [comment]
Issue resolved in c72e0c44e48f331b8ac6dd3ce6406b45af2ab508 using the new template stitching workflow
